[book]
authors = ["sunrisepeak"]
language = "en"
multilingual = false
src = "src"
title = "D2X Project Template | D2X项目模板"

[output.html]
git-repository-url = "https://github.com/d2learn/d2x-project-template"
